schema: "classroom50/repo-config/v1"
classroom: "f215-digital-design"
assignment: "dd-2026-verilog-labs"
owner:
  username: "YPGA30068"
  id: 318479734
  accepted_at: "2026-08-25T10:41:35Z"
source:
  owner: "f2152026"
  owner_id: 316136693
  repo: "verilog-labs"
  branch: "main"
